### ISSUE TITLE
Feature Request: Punycode/IDN Reversal

### ISSUE THREAD

**Issue by ghost** [MarkBaggett/domain_stats#11]
Mark, 

Could you build in an API query function to reverse punycode domains (e.g. xn--bcher-kva.tld) within domain_stats?

The idea is to use Logstash to breakdown domains beginning with "xn--" and reverse it back out to the Unicode to detect cousin domains since the IDN wont appear in the logs only the ASCII will and it would be useful to see if someone is abusing a "look-a-like".

Thanks for your hard work on the domain_stats and freq_server projects!

**Comment by MarkBaggett** [comment]
Hi,
Thanks for the request.   Id love to add this for you, but I'm not exactly sure what you need.  Decoding these in python3 is pretty easy.  

`>>> b"xn--i-7iq.python".decode("idna")`
'i❤.python'
`>>> b"xn--n28h".decode("idna")`
'😉'

I'm not exactly sure how this would work in practice.  Lets say that I expose an API like this..

http://ip:port/punycode/xn--i-7iq.python

and I return unicode characters of 'i❤.python' does that do what you need?   When you feed these unicode characters in into any log analyzer that doesn't support unicode what happens?   

I appreciate your help.

**Comment by ghost** [comment]
The API exposed like this would work perfect. what I would like to do with one of Justin Henderson's Logstash configs is to augment the DNS postprocess (https://github.com/HASecuritySolutions/Logstash/blob/master/configfiles/8006_postprocess_dns.conf) to use the TLD plugin for Logstash and break down the DNS query then make IF statements to regex look for ^xn-- and feed it to the API.

Top Level Domain
hxxp://ip:port/punycode/xn--i-7iq

Parent Domain (if its punycode)
hxxp://ip:port/punycode/xn--s7y

**Comment by MarkBaggett** [comment]
Can you test this one out for me and give me some feedback?

[domain_stats.txt](https://github.com/MarkBaggett/domain_stats/files/2388741/domain_stats.txt)

How you consume the results will determine the usefulness of this features.   You can see here that firefox doesn't like the response but the developer tools and curl give me the answer I think you want.

![domain_stats_punycode_feature](https://user-images.githubusercontent.com/743693/45626252-101f1f00-ba5d-11e8-98f0-4bb8eff905fe.png)

**Comment by MarkBaggett** [comment]
HI N7FAA52318 
Can you confirm that punycode patch posted in my last reply does what you are looking for.

**Comment by MarkBaggett** [comment]
N7FAA52318
You asked me for a feature.  I wrote your feature.  If you would please do me the courtesy responding to me and/or testing to confirm this does what you want, I would appreciate it.  I would like to close this ticket and publish the feature in the main code branch if it is working properly.  Thanks

**Comment by ghost** [comment]
Mark,
I was able to come to the same result that it would not render properly in a web browser. I had tried with Chrome, IE, and Firefox. It did render the Unicode in the terminal fine. I am still working on a Logstash config to parse a bro DNS log to see if it will show correctly in Kibana.

Sorry for the late reply.

**Comment by MarkBaggett** [comment]
no problem.   Thanks for the update.  For the characters to render properly in a browser the HTML will have to contain 
```
< meta charset="utf-8"/ >
```
Since I'm only returning the UTF-8 it wont render in browsers but it should be OK when stuffed into Kibana as long as kabana has that HTML in it's
```
<HEAD>
```
section.

I'll leave the ticket open for another 30 days and if I don't hear back from you i'll assume it isn't going to be useful and delete it.   Two questions for you.

1) Is 30 days about right or do you need longer for the logstash config?
2) I'll mention this feature when I give a presentation at Security Onion Con in two weeks (Oct 19) and solicit additional feedback.  Are you ok with me mentioning your github handle? Im assuming so since all these conversations are public on github but I want to ask.  Is there anything about this feature you would like me to point out or mention in that talk?

**Comment by ghost** [comment]
Mark,
I don't mind about the mention. I'm still running into a slight output problem with Logstash.

I've attached my rudimentary Logstash configuration, the output it is giving me, and the single Bro log I am using for testing which should output the domain apple.com with the "alpha" character for the first "a"

I still think the feature is very useful used in a manual way for now by grepping and bro-cutting the domains that begin with "xn--" and running those through a for loop to output the IDNs in a terminal.

Maybe someone with more experience in Logstash than me knows how to easily mutate that field into a different character set but I will keep digging.

Thank you for your help and support on this and good luck at Security Onion Con!

![sec555-2018-10-16-20-53-13](https://user-images.githubusercontent.com/28744015/47055655-8ca13c80-d186-11e8-82bf-07af2b16103e.png)

[puny.log](https://github.com/MarkBaggett/domain_stats/files/2485437/puny.log)

[punycode_conf.txt](https://github.com/MarkBaggett/domain_stats/files/2485441/punycode_conf.txt)
