### ISSUE TITLE
Upstart config file

### ISSUE THREAD

**Issue by reswob10** [MarkBaggett/domain_stats#13]
One of the CentOS 6 servers uses upstart.  Here's the conf file I put in /etc/init/ to run this as a service:

```
description     "Domain Stats"
start on filesystem or runlevel [2345]
stop on runlevel [!2345]

respawn

script
      export HOME="/usr/bin"
      echo $$ > /var/run/domainstats.pid
      exec python /opt/domain-stats/domain_stats.py -ip <IP> -preload 0 -a /opt/domain-stats/top-1m.csv 8002
end script

pre-start script
      echo "[`date`] Domain Stats starting" >> /var/log/messages
end script

pre-stop script
      echo "[`date`] Domain Stats stopping" >> /var/log/messages
end script
```

**Comment by reswob10** [comment]
Some information about using this:  
https://www.digitalocean.com/community/tutorials/the-upstart-event-system-what-it-is-and-how-to-use-it

**Comment by MarkBaggett** [comment]
Thank you for the submittion.  The code base has been completely rewritten and this is currently incompatible with the code.
