### ISSUE TITLE
Code Rewrite

### ISSUE THREAD

**Issue by tbennett6421** [MarkBaggett/domain_stats#19]
I'd recommend your rewrite from ISC be it's own repository. Github does not allow forking a repository more then once and a significant code shift could break forked repos.

Otherwise people will need to clone your repo, create a new branch at the latest stable and duplicate the repository and remove all forking information.

Thank you for all the work you do for the infosec community.

**Comment by MarkBaggett** [comment]
Hi Tyler,
Id like to get a better understanding of what your telling me. 

I did mark the original version as a 'release'.
https://github.com/MarkBaggett/domain_stats/releases

I also plan to leave the old branch out there forever.
https://github.com/MarkBaggett/domain_stats/tree/domain_stats_1

I think you will be able to do everything you need with that, but I may be missing something.

**Comment by tbennett6421** [comment]
okay, that should be fine then.
