### ISSUE TITLE
Feature Request:  Add domains to cache that return "No whois record for <domain>"

### ISSUE THREAD

**Issue by reswob10** [MarkBaggett/domain_stats#7]
When a whois request for  a domain returns, "No whois record for <domain>", that response is not cached.  This means that when that domain is queried again, domain_stats makes another whois query.  This really slows down scripts making making multiple requests.  I suggest caching this response for a set period of time (i.e. one day or one week).  This will speed things up when running multiple requests, yet still allow for occasional checking for updated information.

**Comment by MarkBaggett** [comment]
Feature Added in 1.1.   Thanks for the request.  Sorry it took so long.
